[package]
name = "database_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.7.0"
getrandom = { version = "0.2", features = ["js"] }
serde = "1.0.188"
